Rails:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/RegexpLiteral:
  Enabled: false

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
